// ================= AI ???? =================
function getRandomMove() { const e=[]; for(let r=0; r<BOARD_SIZE; r++) { for(let c=0; c<BOARD_SIZE; c++) { if(board[r][c]===EMPTY && !isZoneRestricted(r,c,currentPlayer)) { e.push({r,c}); } } } return e.length ? e[Math.floor(Math.random()*e.length)] : null; }
function getScoreMove(adv, mas=false) { let max = -Infinity; let ms = []; const ai = currentPlayer; const hum = currentPlayer === MAPLE ? SUN : MAPLE; for(let r=0; r<BOARD_SIZE; r++) { for(let c=0; c<BOARD_SIZE; c++) { if(board[r][c]!==EMPTY || isZoneRestricted(r,c,ai) || !hasNeighbor(r,c)) continue; let a = evalPt(r, c, ai); let d = evalPt(r, c, hum); let s = 0; if (!adv) { s = a + d; } else { s = a * (mas ? 1.2 : 1) + d; if(a >= 1e5) s = Infinity; else if(d >= 1e5) s = 9e7; else if(a >= 1e4) s += 5e4; else if(d >= 1e4) s += 4e4; } s += Math.random() * 10; if (s > max) { max = s; ms = [{r, c}]; } else if (Math.abs(s - max) < 5) { ms.push({r, c}); } } } return ms.length ? ms[Math.floor(Math.random()*ms.length)] : getRandomMove(); }
function evalPt(r, c, t) { let s = 0; const directions = [[1,0], [0,1], [1,1], [1,-1]]; directions.forEach(d => { s += getLn(r, c, d[0], d[1], t); }); return s; }
function getLn(r, c, dr, dc, t) { let ct = 1; let es = 0; let i = 1; while(isValid(r + dr*i, c + dc*i) && board[r + dr*i][c + dc*i] === t) { ct++; i++; } if(isValid(r + dr*i, c + dc*i) && board[r + dr*i][c + dc*i] === EMPTY) es++; i = 1; while(isValid(r - dr*i, c - dc*i) && board[r - dr*i][c - dc*i] === t) { ct++; i++; } if(isValid(r - dr*i, c - dc*i) && board[r - dr*i][c - dc*i] === EMPTY) es++; const winLen = shortBattleTurns > 0 ? 4 : 5; if(ct >= winLen) return 1e5; if(ct === winLen - 1) return es === 2 ? 1e4 : (es === 1 ? 1e3 : 0); if(ct === winLen - 2) return es === 2 ? 1e3 : (es === 1 ? 100 : 0); if(ct === winLen - 3) return es === 2 ? 100 : 0; return 0; }
function hasNeighbor(r, c) { for(let i=r-2; i<=r+2; i++) { for(let j=c-2; j<=c+2; j++) { if(isValid(i,j) && board[i][j]!==EMPTY) return true; } } return false; }

if (window.GameHost && typeof window.GameHost.register === 'function') {
    window.GameHost.register('ai', { init: function() {} });
}
